version: "3.1"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: bitnami-zookeeper_3_8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    networks:
      - messages
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.2
    container_name: bitnami-kafka_3_2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - messages
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  app:
    build:
      context: ./app
    networks:
      - messages
    container_name: messages-app
    restart: always
    ports:
      - "8080:8080"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  messages:
    driver: bridge